Add controllers
naumich1984/ShareIt pull request #1
Opened 2024-02-03 09:52 UTC by naumich1984

add ShareIt app

2024-02-04 04:49 UTC, avlin87 requested changes
Привет, Алексей,
Работа выгладит хорошо, есть только незначительные недочеты.
Поправь, пожалуйста.

2024-02-04 04:49 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +@RequiredArgsConstructor
`@RequiredArgsConstructor` создает конструктор для **private final** полей.
В нашем классе нет таких полей
Неиспользуемый код лучше удалять, для чистоты кода.

2024-02-04 04:49 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +    private UserService userService;
Переменная не используется в этом классе - такое лучше удалять для чистоты кода.

2024-02-04 04:49 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/User.java
> +@RequiredArgsConstructor()
Данная аннотация излишня. Убери, пожалуйста.

2024-02-04 04:59 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +@RequiredArgsConstructor
Александр, привет. Исправил.

2024-02-04 04:59 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/item/ItemInMemoryStorage.java
> +    private UserService userService;
Исправил

2024-02-04 04:59 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/user/User.java
> +@RequiredArgsConstructor()
Исправил

2024-02-05 03:33 UTC, avlin87 approved these changes
Работу принимаю.

2024-02-05 05:23 UTC, merged