Add item requests
naumich1984/ShareIt pull request #4
Opened 2024-03-10 10:39 UTC by naumich1984

add item-requests

2024-03-17 16:27 UTC, avlin87 requested changes
Привет, Алексей,
Хорошая работа, автоматические проверки выполняются.
Комментариев 3~4 остальные повторяются, старался отметить все места.

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
`Можно лучше`
Так как мы используем lombok в нашей работе, то можно воспользоваться аннотацией `@EqualsAndHashCode` тут и в других подобных классах и настроить её в соответствии с нашими нуждами дополнительными параметрами
[ссылка на статью](https://www.baeldung.com/java-lombok-equalsandhashcode)

Пример - указываем участвующие поля на уровне аннотации класса:
```
@EqualsAndHashCode(of = {"name", "id"})
public class Employee {
    private String name;
    private int id;
    private int age;
}
```
_в статье приведены и другие варианты настройки этой аннотации, может тебе како-то другой вариант понравится больше._

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInfo.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> -@RequestMapping(path = "/requests")
Верни, пожалуйста, аннотацию `@RequestMapping(path = "/requests")`
А в аннотациях методов удали `"/requests"` часть.

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    public boolean equals(Object o) {
`можно лучше`
Можно заменить эти методы аннотацией из библиотеки lombok

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/User.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public boolean equals(Object o) {
`Можно лучше`
можно воспользоваться аннотацией `@EqualsAndHashCode`

2024-03-17 16:27 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
`Можно лучше`
В тестовом классе лучше для постоянства лучше сделать уровень доступа переменных одинаковый, например private.

2024-03-17 16:27 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingController bookingController;
`Можно лучше`
В тестовом классе лучше для постоянства лучше сделать уровень доступа переменных одинаковый, например private.

2024-03-17 16:27 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceTest.java
> +    ItemRequestServiceImpl itemRequestService;
`Можно лучше`
В тестовом классе лучше для постоянства лучше сделать уровень доступа переменных одинаковый, например private.

2024-03-17 16:27 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/user/UserServiceTest.java
> +    UserServiceImpl userService;
`Можно лучше`
В тестовом классе лучше для постоянства лучше сделать уровень доступа переменных одинаковый, например private.

2024-03-18 11:18 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    public boolean equals(Object o) {
Александр, привет. Спасибо за совет. Код стал более читаемый.

2024-03-18 11:18 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    public boolean equals(Object o) {
Исправил.

2024-03-18 11:18 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInfo.java
> +    public boolean equals(Object o) {
Исправил.

2024-03-18 11:18 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    public boolean equals(Object o) {
Исправил.

2024-03-18 11:19 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    public boolean equals(Object o) {
Исправил.

2024-03-18 11:19 UTC, naumich1984 commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public boolean equals(Object o) {
Исправил.

2024-03-18 11:19 UTC, naumich1984 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
Исправил.

2024-03-18 11:19 UTC, naumich1984 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingController bookingController;
Исправил.

2024-03-18 17:58 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-19 02:09 UTC, merged